import './style.css';
import { initializeApp } from 'firebase/app';
import { getAuth, signInAnonymously } from 'firebase/auth';
import { getDatabase, ref, set, onValue, push, onDisconnect, update } from 'firebase/database';

type Mode='ai'|'practice'|'online';
const cfg={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,databaseURL:import.meta.env.VITE_FIREBASE_DATABASE_URL,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
let db:any=null, uid='local-'+Math.random().toString(36).slice(2), room='';
if(cfg.apiKey&&cfg.databaseURL){try{const app=initializeApp(cfg);db=getDatabase(app);signInAnonymously(getAuth(app)).then(x=>uid=x.user.uid).catch(()=>{});}catch{}}

const root=document.querySelector('#app')!; root.innerHTML=`<main><header><div class="brand"><span class="mark">✦</span><div><b>FOOSBALL</b><small>ARENA</small></div></div><div class="status"><i></i><span id="net">LOCAL PLAY</span></div></header><section class="hero"><div><p class="eyebrow">ARCADE TABLE // 01</p><h1>Own the<br><em>table.</em></h1><p class="sub">Fast hands. Smart angles.<br>First to the finish.</p></div><div class="ball-art">⚽</div></section><section class="cards"><button class="mode active" data-mode="ai"><span>◈</span><strong>VS AI</strong><small>Sharpen your game</small></button><button class="mode" data-mode="online"><span>◎</span><strong>ONLINE</strong><small>Play with a friend</small></button><button class="mode" data-mode="practice"><span>△</span><strong>PRACTICE</strong><small>Master the controls</small></button></section><section class="match"><div><label>WIN CONDITION</label><div class="goals"><button data-goals="3">3</button><button class="selected" data-goals="5">5</button><button data-goals="7">7</button></div></div><div class="online-box" id="onlineBox"><input id="room" placeholder="ROOM CODE" maxlength="6"><button id="join">JOIN / CREATE</button></div><button class="play" id="play">PLAY NOW <span>→</span></button></section><p class="hint">DRAG TO MOVE YOUR RODS <b>•</b> TILT TO SHOOT</p></main><div class="game hidden"><canvas id="canvas"></canvas><div class="hud"><button id="back">← MENU</button><div class="score"><span id="me">0</span><small>—</small><span id="op">0</span></div><div class="round">FIRST TO <b id="target">5</b></div></div><div class="game-tip">DRAG ANYWHERE TO MOVE • TAP TO SHOOT</div></div>`;
const $=(s:string)=>document.querySelector(s) as HTMLElement; let mode:Mode='ai', target=5; document.querySelectorAll('.mode').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(y=>y.classList.remove('active'));x.classList.add('active');mode=x.getAttribute('data-mode') as Mode;$('#onlineBox').classList.toggle('show',mode==='online');})); document.querySelectorAll('[data-goals]').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('[data-goals]').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');target=Number(x.getAttribute('data-goals'));$('#target').textContent=String(target);}));
$('#join').onclick=()=>{room=(($('#room') as HTMLInputElement).value||Math.random().toString(36).slice(2,8)).toUpperCase();($('#room') as HTMLInputElement).value=room; $('#net').textContent='ROOM '+room;}; $('#play').onclick=()=>start(); $('#back').onclick=()=>{($('.game') as HTMLElement).classList.add('hidden');(document.querySelector('main') as HTMLElement).classList.remove('hidden');};
const canvas=$('#canvas') as HTMLCanvasElement, ctx=canvas.getContext('2d')!; let W=1200,H=600, ball={x:600,y:300,vx:5,vy:2}, score=[0,0], rods=[180,340,520,700,860,1020], dragging=false, lastY=0, raf=0;
function start(){(document.querySelector('main') as HTMLElement).classList.add('hidden');($('.game') as HTMLElement).classList.remove('hidden'); resize(); score=[0,0]; ball={x:600,y:300,vx:5,vy:2}; if(mode==='online'&&db){const r=ref(db,'rooms/'+room);set(ref(db,'rooms/'+room+'/players/'+uid),{joinedAt:Date.now(),name:'Player'});onDisconnect(ref(db,'rooms/'+room+'/players/'+uid)).remove();onValue(ref(db,'rooms/'+room+'/score'),s=>{if(s.exists())score=s.val();});} cancelAnimationFrame(raf); loop();}
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';}
function loop(){ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0); draw(); ball.x+=ball.vx;ball.y+=ball.vy;ball.vx*=.998;ball.vy*=.998;if(ball.y<70||ball.y>530)ball.vy*=-1;if(ball.x<40){score[1]++;reset();}if(ball.x>1160){score[0]++;reset();}$('#me').textContent=String(score[0]);$('#op').textContent=String(score[1]); if(mode==='ai'){rods[4]+=(ball.y-rods[4])*.015;rods[5]+=(ball.y-rods[5])*.02;} if(db&&mode==='online'&&room)update(ref(db,'rooms/'+room),{score});raf=requestAnimationFrame(loop);}
function reset(){ball={x:600,y:300,vx:(Math.random()>.5?5:-5),vy:(Math.random()-.5)*5};}
function draw(){const g=ctx;g.fillStyle='#07131a';g.fillRect(0,0,W,H);g.fillStyle='#9a5d31';g.fillRect(18,42,1164,516);g.fillStyle='#10242a';g.fillRect(35,58,1130,484);g.fillStyle='#1b754f';g.fillRect(55,78,1090,444);g.strokeStyle='#d7f2df';g.lineWidth=4;g.strokeRect(55,78,1090,444);g.beginPath();g.moveTo(600,78);g.lineTo(600,522);g.arc(600,300,80,0,Math.PI*2);g.stroke();g.strokeRect(55,205,120,190);g.strokeRect(1025,205,120,190);g.fillStyle='#06161a';g.fillRect(35,245,20,110);g.fillRect(1145,245,20,110);rods.forEach((x,i)=>{g.strokeStyle='#c5d3d2';g.lineWidth=7;g.beginPath();g.moveTo(x,60);g.lineTo(x,540);g.stroke();const y=300+(i%2?40:-30);g.fillStyle=i<3?'#3d8fff':'#f2545b';g.fillRect(x-16,rods[i]-8,32,32);g.beginPath();g.arc(x,rods[i]-18,12,0,Math.PI*2);g.fill();});g.fillStyle='#fff';g.beginPath();g.arc(ball.x,ball.y,14,0,Math.PI*2);g.fill();g.fillStyle='#17242a';g.beginPath();g.arc(ball.x-4,ball.y-3,4,0,Math.PI*2);g.fill();}
canvas.onpointerdown=e=>{dragging=true;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(dragging){const dy=e.clientY-lastY;rods[2]=Math.max(110,Math.min(490,rods[2]+dy*1.5));rods[3]=Math.max(110,Math.min(490,rods[3]+dy*1.5));lastY=e.clientY;}};canvas.onpointerup=()=>dragging=false;canvas.ondblclick=()=>{ball.vx+=ball.vx>0?5:-5;ball.vy+=(Math.random()-.5)*4;};addEventListener('resize',resize);
